services:
  qemu:
    image: qemux/qemu
    container_name: ubuntu10
    environment:
      #BOOT: "arch"
      #BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-virt-3.19.1-x86_64.iso"
      #BOOT: "https://old-releases.ubuntu.com/releases/lucid/ubuntu-10.04-desktop-amd64.iso"
      #BOOT: "https://old-releases.ubuntu.com/releases/lucid/ubuntu-10.04.4-server-amd64.iso"
      #BOOT: "https://old-releases.ubuntu.com/releases/maverick/ubuntu-10.10-desktop-amd64.iso"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "22G"
      #QEMU_ARGS: "-vga std -display vnc=0.0.0.0:0 -append 'textonly nomodeset vga=normal'"
      #QEMU_ARGS: "-bios /usr/share/seabios/bios.bin -machine accel=kvm -vga std -display vnc=0.0.0.0:0 -append 'nomodeset nofb vga=normal'"
      #QEMU_ARGS: "-vga std -display vnc=0.0.0.0:0 -append 'nomodeset nofb vga=788 console=tty0 console=ttyS0'"
      #QEMU_ARGS: "-nographic -serial mon:stdio -append 'auto url=file:///preseed/preseed.cfg console-setup/ask_detect=false console-setup/layoutcode=us'"
      #QEMU_ARGS: "-vga std -display vnc=0.0.0.0:0 -append 'nomodeset nofb vga=normal'"
      #QEMU_ARGS: "-nographic -serial mon:stdio -append 'console=ttyS0'"
      #QEMU_ARGS: "-vga cirrus -display vnc=0.0.0.0:0 -boot d -kernel /isolinux/vmlinuz -initrd /isolinux/initrd.img -append 'priority=critical locale=en_US console-setup/ask_detect=false console-setup/layoutcode=us console-setup/variantcode=us keyboard-configuration/layoutcode=us interface=auto url=http://localhost/preseed.cfg vga=normal fb=false'"
      #QEMU_ARGS: "-vga cirrus -display vnc=0.0.0.0:0 -k en-us"
      BOOT_ORDER: "dc"
      #CPU_TYPE: "qemu64"
      USERNAME: "arch"
      PASSWORD: "arch"
      GPU: "Y"
      #DISK_FILE: "./storage/data.img"
    devices:
      - /dev/dri
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 2222:22
    volumes:
      - ./storage/arch/boot.iso:/boot.iso
      #- ./../../../ubuntu-mate-remix-2026.06.29-x86_64.iso:/boot.iso
      #- ./preseed.cfg:/preseed/preseed.cfg
      #- ./example.iso:/boot.iso
      - ./storage:/storage
      - ./shared:/shared
    restart: always
    stop_grace_period: 2m
